### ISSUE TITLE
Other vehicles support

### ISSUE THREAD

**Issue by carlodonzelli** [major/toyota-inventory#11]
Thanks for this service! Very cool. Would you be able to branch out for other models as well? Like a Tacoma for example :)

**Comment by major** [comment]
@carlodonzelli You're welcome. You might like my [newer repository](https://github.com/major/yotagrabber/).

You can view the [Tacoma data](https://flatgithub.com/major/yotagrabber?filename=output%2Ftacoma.csv&sha=fdbc31827aac10ca52f961963663a5a02eb2aca0) and sort it however you like. :wink:
